version: '3.2'

volumes:
  mysql-data:

services:
  node:
    build: .
    environment:
      PORT: 3000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "projetWeb"  # Nom de la base de données à utiliser
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mariadb
    container_name: monmysql
    environment:
      MYSQL_ROOT_PASSWORD: "manon"
      MYSQL_DATABASE: "projetWeb"  # Nom de la base de données à créer
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "manon"  # Mot de passe root MySQL
    ports:
      - "8081:80"  # Port pour accéder à phpMyAdmin depuis le navigateur
    depends_on:
      - mysql
