version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOTUSER=root
      - MYSQL_DATABASE=projetWeb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=manon
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80

  web:
    build: .
    ports:
      - '3000:3000'
    #volumes:
     # - ./site_annonces:/app
    depends_on:
      - db