version: '3.2'

volumes:
  mysql-data:

services:
  node:
    build: .
    environment:
      PORT: 3000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "projetWeb"  
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mariadb
    container_name: monmysql2
    environment:
      MYSQL_ROOT_PASSWORD: "manon"
      MYSQL_DATABASE: "projetWeb"  
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
