version: '3.2'
volumes:
  mysql-data:

services:
  node:
    build: .
    environment:
      PORT: 3000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "database"
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: "manon"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306