version: '3'

services:
  monnode:
    container_name: monnode-lerman
    image: monnode
    ports:
      - "8082:8080"
    restart: always

  monmysql:
    container_name: monmysql
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manon

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: monmysql
      MYSQL_ROOT_PASSWORD: manon
